# Generated by Django 4.1.7 on 2023-02-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_image_place_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='img',
        ),
    ]
