# Generated by Django 4.1.7 on 2023-02-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_newplace_remove_place_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
