# Generated by Django 4.1.7 on 2023-02-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_delete_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newplace',
        ),
    ]
